packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    commander: ^14.0.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    postcss: ^8.5.5
    prompts: ^2.4.2
    simple-git-hooks: ^2.11.1
    tsdown: ^0.12.4
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.13.10
    '@types/prompts': ^2.4.9
    '@types/stringify-object': ^4.0.5
  utils:
    cosmiconfig: ^9.0.0
    deepmerge: ^4.3.1
    fast-glob: ^3.3.3
    fs-extra: ^11.3.0
    https-proxy-agent: ^7.0.6
    kleur: ^4.1.5
    node-fetch: ^3.3.2
    ora: ^8.2.0
    stringify-object: ^5.0.0
    tailwindcss: ^4.1.10
    tinyexec: ^0.3.2
    ts-morph: ^26.0.0
    tsconfig-paths: ^4.2.0
    type-fest: ^4.41.0
    zod: ^3.25.64
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
