// eslint-disable-next-line ts/ban-ts-comment
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import type { EnvironmentInjector } from '@angular/core'
import { createComponent } from '@angular/core'

export const Index: Record<string, any> = {
  index: {
    name: 'index',
    description: '',
    type: 'registry:style',
    registryDependencies: ['utils'],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  style: {
    name: 'style',
    description: '',
    type: 'registry:style',
    registryDependencies: ['utils'],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  utils: {
    name: 'utils',
    description: '',
    type: 'registry:lib',
    registryDependencies: undefined,
    files: [{
      path: 'registry/new-york-v4/lib/utils.ts',
      type: 'registry:lib',
      target: '',
    }],
    component: async (environmentInjector: EnvironmentInjector) => {
      const mod = await import('@/registry/new-york-v4/lib/utils.ts')
      const exportName = Object.keys(mod).find((key) => {
        const value = (mod as Record<string, unknown>)[key]
        return typeof value === 'function' && value.prototype && value.prototype.constructor === value
      })
      return createComponent(mod[exportName as keyof typeof mod], {
        environmentInjector,
      })
    },
    categories: undefined,
    meta: undefined,
  },
}
