export const ERRORS = {
  MISSING_DIR_OR_EMPTY_PROJECT: 'MISSING_DIR_OR_EMPTY_PROJECT',
  UNSUPPORTED_FRAMEWORK: 'UNSUPPORTED_FRAMEWORK',
  TAILWIND_NOT_CONFIGURED: 'TAILWIND_NOT_CONFIGURED',
  IMPORT_ALIAS_MISSING: 'IMPORT_ALIAS_MISSING',
}
