import type { Registry } from 'shadcn-ng/registry'

export const examples: Registry['items'] = [
  {
    name: 'accordion-demo',
    type: 'registry:example',
    registryDependencies: ['accordion'],
    files: [{ path: 'example/accordion-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'alert-demo',
    type: 'registry:example',
    registryDependencies: ['alert'],
    files: [{ path: 'example/alert-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'alert-destructive',
    type: 'registry:example',
    registryDependencies: ['alert'],
    files: [{ path: 'example/alert-destructive.ts', type: 'registry:example' }],
  },
  {
    name: 'aspect-ratio-demo',
    type: 'registry:example',
    registryDependencies: ['aspect-ratio'],
    files: [{ path: 'example/aspect-ratio-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'avatar-demo',
    type: 'registry:example',
    registryDependencies: ['avatar'],
    files: [{ path: 'example/avatar-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'badge-demo',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: [{ path: 'example/badge-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'badge-destructive',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: [{ path: 'example/badge-destructive.ts', type: 'registry:example' }],
  },
  {
    name: 'badge-outline',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: [{ path: 'example/badge-outline.ts', type: 'registry:example' }],
  },
  {
    name: 'badge-secondary',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: [{ path: 'example/badge-secondary.ts', type: 'registry:example' }],
  },
  {
    name: 'breadcrumb-demo',
    type: 'registry:example',
    registryDependencies: ['breadcrumb'],
    files: [{ path: 'example/breadcrumb-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'button-demo',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'button-destructive',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-destructive.ts', type: 'registry:example' }],
  },
  {
    name: 'button-ghost',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-ghost.ts', type: 'registry:example' }],
  },
  {
    name: 'button-icon',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-icon.ts', type: 'registry:example' }],
  },
  {
    name: 'button-link',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-link.ts', type: 'registry:example' }],
  },
  {
    name: 'button-loading',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-loading.ts', type: 'registry:example' }],
  },
  {
    name: 'button-outline',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-outline.ts', type: 'registry:example' }],
  },
  {
    name: 'button-secondary',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-secondary.ts', type: 'registry:example' }],
  },
  {
    name: 'button-with-icon',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [{ path: 'example/button-with-icon.ts', type: 'registry:example' }],
  },
  {
    name: 'card-with-form',
    type: 'registry:example',
    registryDependencies: ['card'],
    files: [{ path: 'example/card-with-form.ts', type: 'registry:example' }],
  },
  {
    name: 'collapsible-demo',
    type: 'registry:example',
    registryDependencies: ['collapsible'],
    files: [{ path: 'example/collapsible-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'dialog-demo',
    type: 'registry:example',
    registryDependencies: ['dialog'],
    files: [{ path: 'example/dialog-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'dropdown-menu-checkboxes',
    type: 'registry:example',
    registryDependencies: ['dropdown-menu'],
    files: [{ path: 'example/dropdown-menu-checkboxes.ts', type: 'registry:example' }],
  },
  {
    name: 'dropdown-menu-demo',
    type: 'registry:example',
    registryDependencies: ['dropdown-menu'],
    files: [{ path: 'example/dropdown-menu-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'dropdown-menu-radio-group',
    type: 'registry:example',
    registryDependencies: ['dropdown-menu'],
    files: [{ path: 'example/dropdown-menu-radio-group.ts', type: 'registry:example' }],
  },
  {
    name: 'input-demo',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: [{ path: 'example/input-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'input-disabled',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: [{ path: 'example/input-disabled.ts', type: 'registry:example' }],
  },
  {
    name: 'input-file',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: [{ path: 'example/input-file.ts', type: 'registry:example' }],
  },
  {
    name: 'pagination-demo',
    type: 'registry:example',
    registryDependencies: ['pagination'],
    files: [{ path: 'example/pagination-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'progress-demo',
    type: 'registry:example',
    registryDependencies: ['progress'],
    files: [{ path: 'example/progress-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'separator-demo',
    type: 'registry:example',
    registryDependencies: ['separator'],
    files: [{ path: 'example/separator-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'skeleton-card',
    type: 'registry:example',
    registryDependencies: ['skeleton'],
    files: [{ path: 'example/skeleton-card.ts', type: 'registry:example' }],
  },
  {
    name: 'skeleton-demo',
    type: 'registry:example',
    registryDependencies: ['skeleton'],
    files: [{ path: 'example/skeleton-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'sonner-demo',
    type: 'registry:example',
    registryDependencies: ['sonner'],
    files: [{ path: 'example/sonner-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'switch-demo',
    type: 'registry:example',
    registryDependencies: ['switch'],
    files: [{ path: 'example/switch-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'table-demo',
    type: 'registry:example',
    registryDependencies: ['table'],
    files: [{ path: 'example/table-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'tabs-demo',
    type: 'registry:example',
    registryDependencies: ['tabs'],
    files: [{ path: 'example/tabs-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'toggle-demo',
    type: 'registry:example',
    registryDependencies: ['toggle'],
    files: [{ path: 'example/toggle-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'textarea-demo',
    type: 'registry:example',
    registryDependencies: ['textarea'],
    files: [{ path: 'example/textarea-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'textarea-disabled',
    type: 'registry:example',
    files: [{ path: 'example/textarea-disabled.ts', type: 'registry:example' }],
  },
  {
    name: 'textarea-with-button',
    type: 'registry:example',
    files: [{ path: 'example/textarea-with-button.ts', type: 'registry:example' }],
  },
  {
    name: 'textarea-with-label',
    type: 'registry:example',
    files: [{ path: 'example/textarea-with-label.ts', type: 'registry:example' }],
  },
  {
    name: 'textarea-with-text',
    type: 'registry:example',
    files: [{ path: 'example/textarea-with-text.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-blockquote',
    type: 'registry:example',
    files: [{ path: 'example/typography-blockquote.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-demo',
    type: 'registry:example',
    files: [{ path: 'example/typography-demo.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-h1',
    type: 'registry:example',
    files: [{ path: 'example/typography-h1.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-h2',
    type: 'registry:example',
    files: [{ path: 'example/typography-h2.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-h3',
    type: 'registry:example',
    files: [{ path: 'example/typography-h3.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-h4',
    type: 'registry:example',
    files: [{ path: 'example/typography-h4.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-inline-code',
    type: 'registry:example',
    files: [{ path: 'example/typography-inline-code.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-large',
    type: 'registry:example',
    files: [{ path: 'example/typography-large.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-lead',
    type: 'registry:example',
    files: [{ path: 'example/typography-lead.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-list',
    type: 'registry:example',
    files: [{ path: 'example/typography-list.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-muted',
    type: 'registry:example',
    files: [{ path: 'example/typography-muted.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-p',
    type: 'registry:example',
    files: [{ path: 'example/typography-p.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-small',
    type: 'registry:example',
    files: [{ path: 'example/typography-small.ts', type: 'registry:example' }],
  },
  {
    name: 'typography-table',
    type: 'registry:example',
    files: [{ path: 'example/typography-table.ts', type: 'registry:example' }],
  },
]
