import type { Registry } from '@/registry/schema'

export const examples: Registry = [
  {
    name: 'accordion-demo',
    type: 'registry:example',
    registryDependencies: ['accordion'],
    files: ['example/accordion-demo.ts'],
  },
  {
    name: 'alert-demo',
    type: 'registry:example',
    registryDependencies: ['alert'],
    files: ['example/alert-demo.ts'],
  },
  {
    name: 'alert-destructive',
    type: 'registry:example',
    registryDependencies: ['alert'],
    files: ['example/alert-destructive.ts'],
  },
  {
    name: 'aspect-ratio-demo',
    type: 'registry:example',
    registryDependencies: ['aspect-ratio'],
    files: ['example/aspect-ratio-demo.ts'],
  },
  {
    name: 'avatar-demo',
    type: 'registry:example',
    registryDependencies: ['avatar'],
    files: ['example/avatar-demo.ts'],
  },
  {
    name: 'badge-demo',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: ['example/badge-demo.ts'],
  },
  {
    name: 'badge-destructive',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: ['example/badge-destructive.ts'],
  },
  {
    name: 'badge-outline',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: ['example/badge-outline.ts'],
  },
  {
    name: 'badge-secondary',
    type: 'registry:example',
    registryDependencies: ['badge'],
    files: ['example/badge-secondary.ts'],
  },
  {
    name: 'breadcrumb-demo',
    type: 'registry:example',
    registryDependencies: ['breadcrumb'],
    files: ['example/breadcrumb-demo.ts'],
  },
  {
    name: 'button-demo',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-demo.ts'],
  },
  {
    name: 'button-destructive',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-destructive.ts'],
  },
  {
    name: 'button-ghost',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-ghost.ts'],
  },
  {
    name: 'button-icon',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-icon.ts'],
  },
  {
    name: 'button-link',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-link.ts'],
  },
  {
    name: 'button-loading',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-loading.ts'],
  },
  {
    name: 'button-outline',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-outline.ts'],
  },
  {
    name: 'button-secondary',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-secondary.ts'],
  },
  {
    name: 'button-with-icon',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: ['example/button-with-icon.ts'],
  },
  {
    name: 'card-with-form',
    type: 'registry:example',
    registryDependencies: ['card'],
    files: ['example/card-with-form.ts'],
  },
  {
    name: 'collapsible-demo',
    type: 'registry:example',
    registryDependencies: ['collapsible'],
    files: ['example/collapsible-demo.ts'],
  },
  {
    name: 'dialog-demo',
    type: 'registry:example',
    registryDependencies: ['dialog'],
    files: ['example/dialog-demo.ts'],
  },
  {
    name: 'input-demo',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: ['example/input-demo.ts'],
  },
  {
    name: 'input-disabled',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: ['example/input-disabled.ts'],
  },
  {
    name: 'input-file',
    type: 'registry:example',
    registryDependencies: ['input'],
    files: ['example/input-file.ts'],
  },
  {
    name: 'progress-demo',
    type: 'registry:example',
    registryDependencies: ['progress'],
    files: ['example/progress-demo.ts'],
  },
  {
    name: 'separator-demo',
    type: 'registry:example',
    registryDependencies: ['separator'],
    files: ['example/separator-demo.ts'],
  },
  {
    name: 'skeleton-card',
    type: 'registry:example',
    registryDependencies: ['skeleton'],
    files: ['example/skeleton-card.ts'],
  },
  {
    name: 'skeleton-demo',
    type: 'registry:example',
    registryDependencies: ['skeleton'],
    files: ['example/skeleton-demo.ts'],
  },
  {
    name: 'sonner-demo',
    type: 'registry:example',
    registryDependencies: ['sonner'],
    files: ['example/sonner-demo.ts'],
  },
  {
    name: 'switch-demo',
    type: 'registry:example',
    registryDependencies: ['switch'],
    files: ['example/switch-demo.ts'],
  },
  {
    name: 'table-demo',
    type: 'registry:example',
    registryDependencies: ['table'],
    files: ['example/table-demo.ts'],
  },
  {
    name: 'tabs-demo',
    type: 'registry:example',
    registryDependencies: ['tabs'],
    files: ['example/tabs-demo.ts'],
  },
  {
    name: 'toggle-demo',
    type: 'registry:example',
    registryDependencies: ['toggle'],
    files: ['example/toggle-demo.ts'],
  },
  {
    name: 'textarea-demo',
    type: 'registry:example',
    registryDependencies: ['textarea'],
    files: ['example/textarea-demo.ts'],
  },
  {
    name: 'textarea-disabled',
    type: 'registry:example',
    files: ['example/textarea-disabled.ts'],
  },
  {
    name: 'textarea-with-button',
    type: 'registry:example',
    files: ['example/textarea-with-button.ts'],
  },
  {
    name: 'textarea-with-label',
    type: 'registry:example',
    files: ['example/textarea-with-label.ts'],
  },
  {
    name: 'textarea-with-text',
    type: 'registry:example',
    files: ['example/textarea-with-text.ts'],
  },
  {
    name: 'typography-blockquote',
    type: 'registry:example',
    files: ['example/typography-blockquote.ts'],
  },
  {
    name: 'typography-demo',
    type: 'registry:example',
    files: ['example/typography-demo.ts'],
  },
  {
    name: 'typography-h1',
    type: 'registry:example',
    files: ['example/typography-h1.ts'],
  },
  {
    name: 'typography-h2',
    type: 'registry:example',
    files: ['example/typography-h2.ts'],
  },
  {
    name: 'typography-h3',
    type: 'registry:example',
    files: ['example/typography-h3.ts'],
  },
  {
    name: 'typography-h4',
    type: 'registry:example',
    files: ['example/typography-h4.ts'],
  },
  {
    name: 'typography-inline-code',
    type: 'registry:example',
    files: ['example/typography-inline-code.ts'],
  },
  {
    name: 'typography-large',
    type: 'registry:example',
    files: ['example/typography-large.ts'],
  },
  {
    name: 'typography-lead',
    type: 'registry:example',
    files: ['example/typography-lead.ts'],
  },
  {
    name: 'typography-list',
    type: 'registry:example',
    files: ['example/typography-list.ts'],
  },
  {
    name: 'typography-muted',
    type: 'registry:example',
    files: ['example/typography-muted.ts'],
  },
  {
    name: 'typography-p',
    type: 'registry:example',
    files: ['example/typography-p.ts'],
  },
  {
    name: 'typography-small',
    type: 'registry:example',
    files: ['example/typography-small.ts'],
  },
  {
    name: 'typography-table',
    type: 'registry:example',
    files: ['example/typography-table.ts'],
  },
]
